#!/bin/sh
#
# PROVIDE: netflow-asstatd
# REQUIRE: DAEMON

# Add the following line to /etc/rc.conf to enable netflow-asstatd:
# netflow_asstatd_enable="YES"
# netflow_asstatd_flags="<set as needed>"

.  /etc/rc.subr

name="netflow_asstatd"
rcvar=`set_rcvar`
command="/usr/local/bin/netflow-asstatd.pl"
command_interpreter="/usr/bin/perl"

load_rc_config $name
# Set defaults
: ${netflow_asstatd_enable="NO"}
: ${netflow_asstatd_pidfile="/var/run/netflow-asstatd.pid"}
: ${netflow_asstatd_port="6343"}
: ${netflow_asstatd_user="root"}

start_cmd="/usr/sbin/daemon -f -u ${netflow_asstatd_user} -p ${netflow_asstatd_pidfile} ${command} -p ${netflow_asstatd_port} ${netflow_asstatd_flags}"
start_postcmd="echo Starting ${name}."

pidfile=${netflow_asstatd_pidfile}

run_rc_command "$1"
